#======================================================================#
#   ____              ____                                             #
#  | __ ) _   _ _   _/ ___| _ __   __ ___      ___ __   ___ _ __ ___   #
#  |  _ \| | | | | | \___ \| '_ \ / _` \ \ /\ / / '_ \ / _ \ '__/ __|  #
#  | |_) | |_| | |_| |___) | |_) | (_| |\ V  V /| | | |  __/ |  \__ \  #
#  |____/ \__,_|\__, |____/| .__/ \__,_| \_/\_/ |_| |_|\___|_|  |___/  #
#         |___/      |_|                                               #
#                                                                      #
#======================================================================#
#
# -- Permissions --
use permissions to mine: true
use permissions to buy: true
use permissions to place: true
#
#
# How do you want to send messages?
use action bar: true
#
#
# How do you want signs to look?
signColors:
  lineOne: '&1'
  lineTwo: '&0'
  lineThree: '&c'
  lineFour: '&0'
#
#
# Do you need Silktouch to mine spawners?
need silktouch: true
#
#
# Can players change spawners with mob eggs?
allow mob egg spawner change: false